### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by farjanakhatuncs** [iniridwanul/Ciraag#24]
Dear developers,
I'm reaching out to express my appreciation for the excellent work you've done on this userbot. I've found it to be extremely helpful. I'm interested in suggesting a new feature that I think would be beneficial to the community. How can I go about submitting a feature request?

**Comment by SharafatKarim** [comment]
@farjanakhatuncs "Your valuable insights will help shape the future of Ciraag. Let's build something great together!"
- iniridwanul,
Developer, Ciraag

Direct URL to discussions,
https://github.com/iniridwanul/Ciraag/discussions/categories/ideas

**Comment by iniridwanul** [comment]
> Dear developers, I'm reaching out to express my appreciation for the excellent work you've done on this userbot. I've found it to be extremely helpful. I'm interested in suggesting a new feature that I think would be beneficial to the community. How can I go about submitting a feature request?

Please share your ideas in the ['Ideas'](https://github.com/iniridwanul/Ciraag/discussions/categories/ideas) section of our GitHub repository's [Discussion](https://github.com/iniridwanul/Ciraag/discussions) tab.

**Comment by farjanakhatuncs** [comment]
> > Dear developers, I'm reaching out to express my appreciation for the excellent work you've done on this userbot. I've found it to be extremely helpful. I'm interested in suggesting a new feature that I think would be beneficial to the community. How can I go about submitting a feature request?
> 
> Please share your ideas in the ['Ideas'](https://github.com/iniridwanul/Ciraag/discussions/categories/ideas) section of our GitHub repository's [Discussion](https://github.com/iniridwanul/Ciraag/discussions) tab.

Thank you Rid sir :)

**Comment by farjanakhatuncs** [comment]
Submit done
@iniridwanul, @SharafatKarim please sir check my request.

**Comment by iniridwanul** [comment]
> Submit done @iniridwanul, @SharafatKarim please sir check my request.

Thank you very much, @farjanakhatuncs, for taking the time to share your valuable insights on improving Ciraag. I have saved your suggestions for future reference and will certainly consider your request.
